# Generated by Django 5.2.14 on 2026-05-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_departure', models.CharField(choices=[('JED', 'Jeddah'), ('MED', 'Medina'), ('DAC', 'Dhaka'), ('CGP', 'Chattogram'), ('ZYL', 'Sylhet')], default='DAC', max_length=3)),
                ('city_arrival', models.CharField(choices=[('JED', 'Jeddah'), ('MED', 'Medina'), ('DAC', 'Dhaka'), ('CGP', 'Chattogram'), ('ZYL', 'Sylhet')], default='JED', max_length=3)),
                ('stay_days', models.IntegerField(choices=[(7, '7 Days'), (10, '10 Days'), (15, '15 Days'), (20, '20 Days'), (30, '30 Days')], default=7)),
                ('timespan_to_search', models.IntegerField(choices=[(7, '7 Days'), (30, '30 Days'), (90, '3 Months'), (180, '6 Months'), (365, '1 Year')], default=30)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('city_departure', models.F('city_arrival')), _negated=True), name='city_departure_not_city_arrival')],
            },
        ),
    ]
