# Generated by Django 5.2.14 on 2026-05-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_search_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='search',
            name='city_departure_not_city_arrival',
        ),
        migrations.AddField(
            model_name='search',
            name='api_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
