# Generated by Django 5.2.14 on 2026-06-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_search_city_departure_not_city_arrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('last_api_call_at', models.DateTimeField()),
            ],
        ),
    ]
